config/routes.rb
Rails.application.routes.draw do
  root to: 'homes#top'
  get 'homes/about' => 'homes#about'
  devise_for :users
  resources :users
  resources :books
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord
  has_one_attached :image
  belongs_to :user
  
  validates :title, presence: true
  validates :body, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
         
  has_many :books, dependent: :destroy
  has_one_attached :profile_image
  
  validates :name, presence: true, length: { minimum: 2 }
  
  def get_profile_image(size)
    unless profile_image.attached?
      file_path = Rails.root.join('app/assets/images/no_image.jpeg')
      profile_image.attach(io: File.open(file_path), filename: 'default-image.jpg', content_type: 'image/jpeg')
    end
    profile_image.variant(resize: size).processed
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  
  before_action :authenticate_user!,except:[:top, :about]
  
  
  before_action :configure_permitted_parameters, if: :devise_controller?
  
   def after_sign_in_path_for(resource)
    user_path(current_user)
  end
  
  def after_sign_out_path_for(resource)
    root_path
  end
  
  private
   
    def configure_permitted_parameters
      devise_parameter_sanitizer.permit(:sign_up, keys:[:email])
    end
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  
  def new
    @book = Book.new
  end
  
  def create
    @book = Book.new(book_params)
    @book.user_id = current_user.id
    if @book.save
      flash[:notice] = "投稿しました"
      redirect_to book_path(@book.id)
    else
      flash[:alert] = "投稿に失敗しました"
      @books = Book.all
      @user = current_user
      @new_book = Book.new
      render :index
    end
  end
  
  def index
    @books = Book.all
    @user = current_user
    @new_book = Book.new
  end
  
  def show
    @book = Book.find(params[:id])
    @user = @book.user
    @new_book = Book.new
  end 
  
  def edit
    @book = Book.find(params[:id])
  end
  
  def update
    @book = Book.find(params[:id])
    @book.update(book_params)
    redirect_to book_path(@book.id)
  end
  
  def destroy
    @book = Book.find(params[:id])
    @book.destroy
    redirect_to books_path
  end
  
  private
  
  def book_params
    params.require(:book).permit(:title, :body, :user_id)
  end
  
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def top
  end
  
  def about
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  
  before_action :edit_button_didden, only: [:edit, :update]
  
  def index
    @users = User.all
    @user = current_user
    @book = Book.new
  end
  
  def show
    @user = User.find(params[:id])
    @books = @user.books
    @new_book = Book.new
  end
  
  def edit
    @user = User.find(params[:id])
  end
  
  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
      flash[:notice] = "You have updated user successfully."
      redirect_to user_path(current_user)
    else
      render :edit
  end
  
  private
  
  def user_params
    params.require(:user).permit(:name, :introduction, :profile_image)
  end
  
  def edit_button_didden
    @user = User.find(params[:id])
    if @user != current_user
      redirect_to user_path(current_user.id)
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/books/_book_list.html.erb
<% books.each do |book| %>
  <tr>
    <td>
      <%= link_to user_path(book.user.id) do %>
        <%= image_tag book.user.get_profile_image("80x80") %>
      <% end %>
    </td>
    <td>
      <%= link_to book.title, book_path(book.id) %>
    </td>
    <td><%= book.body %></td>
  </tr>
<% end %>

app/views/books/edit.html.erb
<p id="notice"></p>
<div class="container">
  <div class="row">
    <div class="col-sm-12 col-md-8 col-lg-5 px-5 px-sm-0 mx-auto">
      <h1>Editing Book</h1>
      <%= form_with model: @book, url: book_path(@book.id), method: :patch do |f| %>
        <div class="form-group">
          <%= f.label :title, "Title" %>
          <%= f.text_field :title, class:"form-control"%>
        </div>
        
        <div class="form-group">
          <%= f.label :body, "Opinion" %>
          <%= f.text_field :body, class:"form-control"%>
        </div>
        
        <%= f.submit "Update Book", class:"btn btn-success" %>
        
      <% end %>
      
      <%= link_to "show", book_path(@book.id) %>
      |
      <%= link_to "Back", books_path %>
  	</div>
  </div>
  </div>
</div>

app/views/books/index.html.erb
<main>
  <p id="notice"></p>
  <div class="container px-5">
    <div class="row">
      <div class="col-md-3">
        <%= render 'users/list', user: @user, book: @book %>
      </div>
      <div class="col-md-8 offset-md-1">
        <h2>Books</h2>
        <table class="table table-hover table-inverse">
          <thead>
            <tr>
              <th></th>
              <th>Title</th>
              <th>Opinion</th>
              <th class="colspan-3"></th>
            </tr>
          </thead>
          <tbodey>
            <%= render 'book_list', books: @books, user: @user %>
          </tbodey>
        </table>
      </div>
    </div>
  </div>
</main>

app/views/books/show.html.erb
<main>
    <p id="notice"></p>
    <div class="container">
        <div class="row">
            <div class="col-md-3">
                <%= render 'users/list', user: @user %>
            </div>
            <div class="col-md-8 offset-md-1">
                <h2>Bookdetail</h2>
                <table class="table">
                    <tbody>
                            <tr>
                                <td>
                                    <%= link_to user_path(@user) do %>
                                        <%= image_tag @book.user.get_profile_image("100x100") %>
                                        <p><%= @book.user.name %></p>
                                    <% end %>
                                </td>
                                <td>
                                    <%= link_to @book.title, book_path(@book.id) %>
                                </td>
                                <td><%= @book.body %></td>
                                <% if @book.user == current_user %>
                                    <td><%= link_to "Edit", edit_book_path(@book.id), class:"btn btn-success" %></td>
                                    <td><%= link_to "Destroy", book_path(@book.id), method: :delete, "data-confirm" => "本当に消しますか？", class:"btn btn-danger" %></td>
                                <% end %>
                            </tr>
                    </tbody>
                </table>
            </div>
      </div>
        </div>
    </div>
</main>

app/views/homes/about.html.erb
<h1>Aboutページ</h1>

app/views/homes/top.html.erb
<main>
  <p id="notice"></p>
  <div class="container">
    <div class="row">
      <div class="mx-auto">
        <h1>welcome to <i class="fas fa-book"></i><strong>Bookers!!</strong></h1>
        <p>In <i class="fas fa-book"></i><strong>Bookers,</strong></p>
        <p>you can share and exchange  your opinions , inpressions , and emotions</p>
        <p> about various books!</p>
        <div class="btn-wrapper col-10 mx-auto">
          <div class="row">
              <%= link_to "Log in", new_user_session_path, class:"btn btn-info btn-sm btn-block mb-3" %>
          </div>
          <div class="row">
              <%= link_to "Sign up", new_user_registration_path, class:"btn btn-success btn-sm btn-block" %>
          </div>
          <div class="row"></div>
        </div>
      </div>
    </div>
  </div>
</main>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Bookers2</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <meta name="viewport" content="width=device-width,initial-scale=1">

    
    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <header>
      <nav class="navbar nvabar-expand-lg navbar-dark bg-dark">
        <div class="container">
          <a class="navbar-brand p-3" href='/'>
            <span>Bookers2</span>
          </a>
          <!--<button class="navbar-toggler collapsed" type="button" data-toggle="collapse" data-target="#navbarNavDropdown"-->
          <!--    aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">-->
          <!--  <span class="navbar-toggler-icon"></span>-->
          <!--</button>-->
          <div class="navbar_collapse collapse show" id="navbarNavDropdown" style="">
            <ul class="navbar-nav ml-auto">
              <% if user_signed_in? %>
                <li>
                  <%= link_to 'Home', user_path(current_user.id) %>
                </li>
                <li>
                  <%= link_to 'Users', users_path %>
                </li>
                <li>
                  <%= link_to 'Book', books_path %>
                </li>
                <li>
                  <%= link_to 'Log out', destroy_user_session_path, method: :delete %>
                </li>
              <% else %>
                <li>
                  <%= link_to 'Home', root_path %>
                </li>
                <li>
                  <%= link_to 'About', homes_about_path %>
                </li>
                <li>
                  <%= link_to 'Sign up', new_user_registration_path %>
                </li>
                <li>
                  <%= link_to 'Log in', new_user_session_path %>
                </li>
              <% end %>
            </ul>
          </div>
        </div>
      </nav>
    </header>
    <div class="text-success">
      <%= flash[:notice] %>
    </div>
    <div class="text-danger">
      <%= flash[:alret] %>
    </div>
    <%= yield %>
    <footer>
      <div class="container mt-5">
        <div class="row">
          <div class="mx-auto">
            <p>CopyRight Infratop.inc</p>
          </div>
        </div>
      </div>
    </footer>
   
   
  </body>
</html>

app/views/users/_list.html.erb
<h2>User info</h2>

  

  <%= image_tag user.get_profile_image("100x100") %>
  <table class="table">
    <tbody>
      <tr>
        <th>name</th>
        <th><%= user.name %></th>
      </tr>
      <tr>
        <th>introduction</th>
        <th><%= user.introduction%></th>
      </tr>
    </tbody>
  </table>
  <div class="row">
    <%# if user == current_user %> 
      <%= link_to edit_user_path(user.id), class: "btn btn-outline-secondary btn-block" do %>
        <i class="fas fa-user-cog"></i>
      <% end %>
    <%# end %>
  </div>
  
  <h2 class="mt-3">New book</h2>
    <%= form_with model: @new_book, local: true  do |f| %>
      <div class="form-group">
        <%= f.label :title, "Title" %>
        <p><%= f.text_field :title, class: "form_control book_title" %></p>
      </div>
     
      <div class="form-group">
        <%= f.label:body, "Opinion" %>
        <p><%= f.text_area :body, class: "form_control book_title" %></p>
      </div>
      <%= f.submit "Create Book", class: "btn btn-success" %>
    <% end %>

app/views/users/edit.html.erb
<main>
  <p id="notice"></p>
  <div class="container">
    <div class="row">
      <div class="col-sm-12 col-md-8 col-lg-5 px-5 px-sm-0 mx-auto">
        <h2>User info</h2>
        <% if @user.errors.any? %>
          <%= @user.errors.count %>件のエラーが発生しました
          <ul>
            <% @user.errors.full_messages.each do |message| %>
              <li><%= message %></li>
            <% end %>
          </ul>
        <% end %>
        <%= form_with model: @user, url: user_path(current_user), method: :patch do |f| %>
          <div class="form-group">
            <%= f.label :name, "Name"%>
            <%= f.text_field :name, class:"form-control"  %>
          </div>
          
          <div class="form-group">
            <%= f.label :profile_image, "Image" %>
            <%= f.file_field :profile_image, accept: "image/*", class:"form-control-file" %>
          </div>
          
          
          <div class="form-group">
            <%= f.label :introduction, "Introduction" %>
            <%= f.text_area :introduction, class:"form-control" %>
          </div>
          
          <%= f.submit "Update User", class:"btn btn-secondary" %>
        <% end %>
      </div>
    </div>
  </div>
</main>

app/views/users/index.html.erb
<main>
  <p id="notice"></p>
  <div class="container px-5">
    <div class="row">
      <div class="col-md-3">
        <%= render 'list', user: @user %>
      </div>
      <div class="col-md-8 offset-md-1">
        <h2>Users</h2>
        <table class="table">
          <thead>
            <tr>
              <th>image</th>
              <th>name</th>
              <th colspan="3"></th>
            </tr>
          </thead>
          <tbody>
            <% @users.each do |user| %>
              <tr>
                <td><%= image_tag user.get_profile_image("100x100") %></td>
                <td><%= user.name %></td>
                <td><%= link_to "Show", user_path(user.id) %></td>
              </tr>
            <% end %>
          </tbody>
        </table>
      </div>
    </div>
  </div>
</main>

app/views/users/shared/_error_messages.html.erb
<% if resource.errors.any? %>
  <div id="error_explanation">
    <h2>
      <%= I18n.t("errors.messages.not_saved",
                 count: resource.errors.count,
                 resource: resource.class.model_name.human.downcase)
       %>
    </h2>
    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/users/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider), method: :post %><br />
  <% end %>
<% end %>

app/views/users/show.html.erb
<main>
  <p id="notice"></p>
  <div class="container px-5">
    <div class="row">
      <div class="col-md-3">
        <%= render 'list', user: @user, new_book: @new_book %>
      </div>
      <div class="col-md-8 offset-md-1">
        <h2>Bookers</h2>
        <table class="table table-hover table-inverse">
          <thead>
            <tr>
              <th></th>
              <th>Title</th>
              <th>Opinion</th>
              <th colspan="3"></th>
            </tr>
          </thead>
          <tbody>
            <%= render 'books/book_list', books: @books, user: @user %>
          </tbody>
        </table>
      </div>
    </div>
  </div>
</main>